### ISSUE TITLE
Diffing Jupyter Notebooks

### ISSUE THREAD

**Issue by sirexeclp** [sirexeclp/ml-in-prec-med#3]
Diffing notebooks is a nightmare.
We could use plain python instead, like Pycharm renders it.

**Comment by alyonavyshnevska** [comment]
do you mean that:
a) when we open jupyter notebook files in pyCharm, and then diff them directly in pycharm? 
b) or do you mean that pycharm can convert the notebooks into plain python, and we work with plain python. When submitting can PyCharm convert it back to notebook (what does it do to markdown files)?

**Comment by sirexeclp** [comment]
I found these two tools:

- https://github.com/mwouts/jupytext
- https://github.com/jupyter/nbdime

First one is for generating plain python or markdown files from notebooks. It can also then update the original notebook. Second one is just a better diff tool.
I didn't really get jupytext to do what i want though.
Which is still having a notebook (in Pycharm) but not in a notebook format.

Pycharm can also run interactively on normal python files, which might do the trick.
I really like the way Pycharm renders notebooks. Would be cool to use this format internally and just generate a notebook file, when we need to submit it.
Problem is: How to convince Pycharm to run a notebook that is actually stored the same way, that it shows the code.
